### PR TITLE
Bump broccoli-filter

### PR DESCRIPTION
**Pull request by josemarluedke**
It contains many bug fixes and performance improvements. 

I also changed the version of this package so you can release a new version.

Thanks

### CODE REVIEW

**Comment by josemarluedke** [comment]
ping @ghempton.

**Comment by josemarluedke** [comment]
Hey @ghempton mind release a new version to NPM?

**Comment by ghempton** [comment]
Done

**Comment by josemarluedke** [comment]
Thank you.

**Pull request merged**
